//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coffeeshop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [Key]
        public int UserID { get; set; }

        [Display(Name = "UserName: ")]
        [Required(ErrorMessage = "Username requierd")]
        public string UserName { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Password: ")]
        [MinLength(6, ErrorMessage = "At least 6 characters needed")]
        public string Password { get; set; }

        [Display(Name = "Confirm Password: ")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Password and confirm password dosen`t match")]
        public string ConfirmPassword { get; set; }


        public bool IsAdmin { get; set; }
    }
}